# Generated by Django 2.2.16 on 2022-08-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220803_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение, относящееся к посту.', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
